### PR TITLE
update embedded-graphics to 0.7.1

### PR DESCRIPTION
**Pull request by FloVanGH**
Update the used embedded-graphics version to 0.7.1

### CODE REVIEW

**Comment by sajattack** [comment]
LOL, CI is failing because the fixed point math slightly changes the drawing of a triangle. We should probably change that.

**Comment by sajattack** [comment]
what the hell why did it close.

**Comment by sajattack** [comment]
@FloVanGH Sorry mate, I accidentally screwed up your branch. I'll open a new pr for this and try to send it back your way as well.

**Comment by overdrivenpotato** [comment]
Thanks for the PR 🙂

**Comment by FloVanGH** [comment]
Glad to help! Thanks for that crate, I think I will have a lot of fun with it :-)

**Comment by FloVanGH** [comment]
By the way, I'm working on a UI toolkit based on embedded-graphics: https://codeberg.org/morphUI/morph_ui. Thanks to your crate I will start with an psp port :-)

**Comment by sajattack** [comment]
:fire: :fire: :fire:

I tried imgui-rs a while back, sorta got it working, but something pure-rust would be awesome!

I got TLS 1.3 working tonight with drogue-tls.

**Comment by sajattack** [comment]
We have a discord chatroom if you'd like to join https://discord.gg/WY8XhDG

**Comment by FloVanGH** [comment]
What could be also interesting is https://github.com/emilk/egui. But I think it does not work with no_std at the moment.

**Pull request closed without merging**
