### PR TITLE
fix: remove `OsStrExt` from psp build script

### LINKED ISSUE #135: cargo psp issue
Is rust-psp not supported on Windows or did I do something wrong? 

> I am using the rustup-init.exe(64-bit) installer

toolchain info:

```
PS C:\Users\diamant3\Desktop\psp-controller> rustup show  
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\diamant3\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.64.0-nightly (93ffde6f0 2022-07-23)
```

systeminfo:

```
PS C:\Users\diamant3\Desktop\psp-controller> systeminfo

Host Name:                 MSI
OS Name:                   Microsoft Windows 11 Home Single Language
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          diamant3
```

bug:

```
PS C:\Users\diamant3\Desktop\psp-controller> cargo psp
   Compiling psp v0.3.1
   Compiling cfg-if v0.1.10
   Compiling alloc v0.0.0 (C:\Users\diamant3\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc)
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> C:\Users\diamant3\.cargo\registry\src\github.com-1ecc6299db9ec823\psp-0.3.1\build.rs:1:20
  |
1 | use std::{env, os::unix::prelude::OsStrExt, path::Path};
  |                    ^^^^ could not find `unix` in `os`

   Compiling unwind v0.0.0 (C:\Users\diamant3\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\unwind)
error[E0599]: no method named `as_bytes` found for struct `OsString` in the current scope
  --> C:\Users\diamant3\.cargo\registry\src\github.com-1ecc6299db9ec823\psp-0.3.1\build.rs:15:10
   |
15 |         .as_bytes()
   |          ^^^^^^^^ method not found in `OsString`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `psp` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
PS C:\Users\diamant3\Desktop\psp-controller> 
```

### PR DESCRIPTION
**Pull request by ZetaNumbers**
Fixes #135

It's practically impossible to have nonunicode rustflags passed into a buildscript

### CODE REVIEW

**Comment by overdrivenpotato** [comment]
Have you tested this on Windows, macOS, and Linux?

**Comment by ZetaNumbers** [comment]
> Have you tested this on Windows, macOS, and Linux? I'm curious if this can break if `RUSTFLAGS` somehow grabs UTF16 paths on Windows.

Rust std assumes windows strings are [wtf-8](https://simonsapin.github.io/wtf-8/), which is basically utf-8 pretending to be utf-16. Since wtf-8 is a superset of utf-8, you can interact with it via any tool with wtf-8 (terminal, shell), which i imagine is majority. Rust std only checks if wtf-8 contains any surrogate code point (pair) and if not, it trivially converts OsString to String. Cargo should use wtf-8 too, so this pr should have the right approach.

I've tested passing Cyrillic on windows via nushell, and it woked as intended.

I am touched by your assumption that i am a CI in the flesh, but i do not have a spare macos system 😉. But since macos is unix, it's the same as for linux (OsStrExt is implemented for unix family).

**Comment by sajattack** [comment]
Speaking of which, I could set up macOS and windows VMs on my server if concourse supports adding those as runners.

**Comment by overdrivenpotato** [comment]
Given that we're going to set up Windows/macOS workers at a later date, I'll merge this.

**Comment by overdrivenpotato** [comment]
Thanks for the PR!

**Pull request merged**
