### PR TITLE
[embedded-graphics] Paint Example

### PR DESCRIPTION
**Pull request by MrAwesome**
Paint Mode

A dead-simple paint program, using the four Playstation controller symbols+colors as brushes.

Controls:
* R/L: Increase/decrease brush size
* Start: Wipe screen
* Analog stick: Move
* Square/Triangle/etc: Change brush

Tinkered around with it long enough to feel like it was a worthy example for the repo - more than happy to polish it up however seems appropriate. Also happy to make it into a separate crate if that feels more appropriate (or more useful to have someone dogfooding a dependency on rust-psp).

Some highlights:
* Deadzone handling for analog stick (does this logic already exist somewhere?)
* Calculation of delta for moving objects on screen around with the analog stick in an intuitive manner
* Stack-based dynamic dispatch example with DrawObj
* Converting numbers to strings with numtoa, to be able to display analog stick values on-screen
* Example of stack-based conversion of slices of u8 to a &str (this was surprisingly difficult to figure out at first for someone without any no_std experience, but now it makes total sense - if you want an owned value on the stack, you need to allocate a known amount of memory to hold your values (in this case a fixed-length array))

### CODE REVIEW

**Comment by sajattack** [comment]
Big ups from me.

**Comment by sajattack** [comment]
@overdrivenpotato noticed while reviewing this that we misspelled Analog in the CtrlMode enum in `psp/src/sys/ctrl.rs`. Would you mind fixing that for us and updating your usage of this enum to the correct spelling?

**Comment by MrAwesome** [comment]
Will do! Fixed up Analaog and Cargo.toml, I'll derive the defaults etc when I get back this afternoon.

**Comment by sajattack** [comment]
Ready to go?

**Comment by MrAwesome** [comment]
Yep! Good to go.

**Comment by sajattack** [comment]
Thanks!

**Comment by overdrivenpotato** [comment]
This is a fantastic example, thanks for the contribution :-)

**Pull request merged**
