### PR TITLE
Fix #135

### LINKED ISSUE #135: cargo psp issue
Is rust-psp not supported on Windows or did I do something wrong? 

> I am using the rustup-init.exe(64-bit) installer

toolchain info:

```
PS C:\Users\diamant3\Desktop\psp-controller> rustup show  
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\diamant3\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.64.0-nightly (93ffde6f0 2022-07-23)
```

systeminfo:

```
PS C:\Users\diamant3\Desktop\psp-controller> systeminfo

Host Name:                 MSI
OS Name:                   Microsoft Windows 11 Home Single Language
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          diamant3
```

bug:

```
PS C:\Users\diamant3\Desktop\psp-controller> cargo psp
   Compiling psp v0.3.1
   Compiling cfg-if v0.1.10
   Compiling alloc v0.0.0 (C:\Users\diamant3\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\alloc)
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> C:\Users\diamant3\.cargo\registry\src\github.com-1ecc6299db9ec823\psp-0.3.1\build.rs:1:20
  |
1 | use std::{env, os::unix::prelude::OsStrExt, path::Path};
  |                    ^^^^ could not find `unix` in `os`

   Compiling unwind v0.0.0 (C:\Users\diamant3\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\unwind)
error[E0599]: no method named `as_bytes` found for struct `OsString` in the current scope
  --> C:\Users\diamant3\.cargo\registry\src\github.com-1ecc6299db9ec823\psp-0.3.1\build.rs:15:10
   |
15 |         .as_bytes()
   |          ^^^^^^^^ method not found in `OsString`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `psp` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
PS C:\Users\diamant3\Desktop\psp-controller> 
```

### PR DESCRIPTION
**Pull request by sajattack**
Untested so far.

Fixes #135 

@diamant3, can you see if this resolves your issue?

### CODE REVIEW

**Comment by diamant3** [comment]
Thank you, I will test it now!

**Comment by ZetaNumbers** [comment]
This shouldn't work

**Comment by diamant3** [comment]
there is another issue :(

is this command correct, i tried ``cargo update`` but the error is the same or did i something wrong?

cargo.toml

```
[package]
name = "psp-controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psp = { git = "https://github.com/overdrivenpotato/rust-psp", branch = "sajattack-patch-1" }

```

error:

```
PS C:\Users\diamant3\Desktop\psp-controller> cargo add --git "https://github.com/overdrivenpotato/rust-psp" --branch "sajattack-patch-1"
    Updating git repository `https://github.com/overdrivenpotato/rust-psp`
    Updating git submodule `https://github.com/rust-lang/llvm-project.git`
        Fetch [===============>         ]  67.04%, (1678065/2813094) resolving deltas   error: failed to update submodule `libunwind/rustc`

Caused by:
  failed to update submodule `src/llvm-project`

Caused by:
  path too long: 'C:/Users/diamant3/.cargo/git/checkouts/rust-psp-0c4563c29347f835/e11e156/libunwind/rustc/src/llvm-project/libcxx/test/std/experimental/utilities/propagate_const/propagate_const.class/propagate_const.non-const_observers/explicit_operator_element_type_ptr.pass.cpp'; class=Filesystem (30)
```

**Comment by ZetaNumbers** [comment]
Try running this command in powershell with elevated privileges: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell#tabpanel_1_powershell

**Comment by diamant3** [comment]
thanks! @ZetaNumbers unfortunately it didn't fix

the ``LongPathsEnabled`` is set to 1 but the issue is the same

Screenshot 2022-07-30 193430

**Pull request closed without merging**
