### PR TITLE
SceWlan Implementation and ethernet example.

### PR DESCRIPTION
**Pull request by NT-Bourgeois-Iridescence-Technologies**
Added the SceWlan module alongside a simple example which prints your switch and wlan device status alongside the IPv6 ethernet address of your device.

### CODE REVIEW

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
Alright, this pull request now also adds the sceRtc functions for real time clock functionality!

**Comment by sajattack** [comment]
Minor nits: Could you surround the parameter names in backticks, and remove the "return stutter" of 
```
# Return value

Return <0 on error.
```
This could be just

```
# Return value

<0 on error.
```

**Comment by sajattack** [comment]
Also, I'm not entirely happy with sce_rtc_check_valid but I'm not sure how to improve it.

**Comment by NT-Bourgeois-Iridescence-Technologies** [comment]
I'm not sure the way you want the i32 to enum implementation, so I leave it to you for decision.

**Pull request merged**
