### PR TITLE
chore(deps): update num_enum & switch to embedded-graphics-core

### PR DESCRIPTION
**Pull request by lorenzofelletti**
Bumps dependencies versions:
- num_enum to `0.7.2`
- embedded-graphics: to `0.8.1`.

### CODE REVIEW

**Comment by sajattack** [comment]
I'm not really sure but maybe we should switch to this? https://crates.io/crates/embedded-graphics-core

**Comment by lorenzofelletti** [comment]
You're probably right...I'll look into it soon

**Comment by lorenzofelletti** [comment]
@sajattack switched to embedded-graphics-core

**Comment by sajattack** [comment]
@lorenzofelletti looks like you missed updating the test in ci that uses it.

**Comment by lorenzofelletti** [comment]
should be fine now @sajattack

**Comment by sajattack** [comment]
Yes looks good. Unfortunately the CI iMac is on the fritz. I'll try to get that fixed up shortly

**Pull request merged**
